name: iit_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_messaging: "^8.0.0-dev.11"
  firebase_storage: ^5.2.0

  esys_flutter_share: ^1.0.2
  google_sign_in: ^4.0.7
  url_launcher: ^5.1.6
  chopper: ^2.4.2
  provider: ^3.0.0+1
  connectivity: ^2.0.2
  built_value: ^6.7.0
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  shared_preferences: ^0.5.6+3
  http: ^0.12.1
  sliding_up_panel: ^1.0.2
  font_awesome_flutter:
  skeleton_text: ^1.0.0
  flutter_spinkit: ^4.1.2
  google_maps_flutter:

  image_picker: ^0.6.7+14
  photo_view: ^0.10.3
  flushbar: ^1.10.4
  clippy_flutter: ^1.1.1
  firebase_dynamic_links: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^2.4.2
  built_value_generator: ^6.7.0
  # No version number means the latest version
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/
